### PR TITLE
use glob rather than recursive-readdir to fetch files in Fuzzy Finder

### LINKED ISSUE #267: Ctrl-P error ENOENT
When I try to push ctrl-p I get a pop-up with this error:
`Error: Error: ENOENT: no such file or directory, stat '/home/nikolay/.config/chromium/SingletonCookie`
and nothing else happens.

### PR DESCRIPTION
**Pull request by keforbes**
This should fix #267, #177, and #125.  `recursive-readdir` has a known issue with broken symlinks but it doesn't look like that defect will ever be fixed.  Use the [node-glob](https://github.com/isaacs/node-glob) library instead.  This library ignores all hidden (`.*`) directories by default so I just added a default ignore of `node_modules` since that directory always has thousands of files in it.  We can tell it to include hidden directories and then explicitly exclude things like `.git`, `.svn`, `.Trash` if we want but I'm not sure if anyone would ever want to look inside hidden directories so this default seems sensible to me.

Also, I added an animated "loading files" indicator in case this takes a while.  The operation is pretty quick after I excluded `node_modules` but I'm sure there will still be still be users with large directories.

### CODE REVIEW

File: browser/src/Services/QuickOpen.ts [hunk 1]
```diff
@@ -40,6 +38,13 @@ export class QuickOpen {
     public show(): void {
         const overrriddenCommand = Config.getValue<string>("editor.quickOpen.execCommand")
 
+        UI.showPopupMenu("quickOpen", [{
```
Comment (extr0py) [inline browser/src/Services/QuickOpen.ts]: Cool idea here to add a loading indicator.

Comment (extr0py) [inline browser/src/Services/QuickOpen.ts]: I logged #269 to build on this and better support async in general with Ctrl-P - it'd be nice to have a gradual loading experience, where you can search results as they are being populated.

File: browser/src/Services/QuickOpen.ts [hunk 2]
```diff
@@ -62,10 +67,12 @@ export class QuickOpen {
                         })
                 } else {
                     // TODO: This async call is being dropped, if we happen to use the promise
-                    return recursiveQ(process.cwd())
-                        .then((files: string[]) => {
-                            this._showMenuFromFiles(files)
-                        })
+                    return glob("**/*", {
```
Comment (extr0py) [inline browser/src/Services/QuickOpen.ts]: Later, for #269, we could use the `match` event to incrementally populate the list.

File: browser/src/Services/QuickOpen.ts [hunk 3]
```diff
@@ -7,18 +7,16 @@
 import { execSync } from "child_process"
 import * as path from "path"
 
+import * as glob from "glob"
```
Comment (extr0py) [inline browser/src/Services/QuickOpen.ts]: Thanks for finding a replacement for `recursive-readdir`. It's a bummer they never wanted to take that PR / fix the issue around handling errors...

File: browser/src/Services/QuickOpen.ts [hunk 4]
```diff
@@ -62,10 +67,12 @@ export class QuickOpen {
...
                     // TODO: This async call is being dropped, if we happen to use the promise
-                    return recursiveQ(process.cwd())
-                        .then((files: string[]) => {
-                            this._showMenuFromFiles(files)
-                        })
+                    return glob("**/*", {
+                        nodir: true,
+                        ignore: ["**/node_modules/**"], // all hidden dirs (start with '.') are skipped by default
+                    }, (_err: any, files: string[]) => {
+                        this._showMenuFromFiles(files)
```
Comment (extr0py) [inline browser/src/Services/QuickOpen.ts]: If there is an error, files might be empty, and then QuickOpen crashes for me. Perhaps we should validate we actually have an array for `files` somewhere

**Comment by extr0py** [comment]
Thanks for this fix, @keforbes ! The loading indicator is a huge improvement.
