### PR TITLE
	modified:   browser/src/index.tsx

### LINKED ISSUE #196: Redo in edit menu not working
@keforbes did some great work in enabling our 'Edit' menu in the toolbar - adding cut, copy, paste, put before/after, etc.

There is a strange issue with `Redo` though - for some reason, `normal! <C-r>` doesn't seem to work as expected. Not sure if this is a neovim bug or something we are doing wrong. It would be interesting to see how vim/gvim behave in that case.

It looks like the `:redo` command works, so we could potentially expand our interface for passing messages to support both `execute` and `normal!` actions (really, the `execute` is a superset anyway) - we'd just have to update our existing messages to match.

### PR DESCRIPTION
**Pull request by bert88sta**
This should fix #196

### CODE REVIEW

**Comment by extr0py** [comment]
Nice, thanks for the fix, @bert88sta ! Looks great

**Comment by keforbes** [comment]
This fix broke `Cut`, `Copy`, and `Paste`.  I'm guessing it's because those options use `"` in their command.

File: browser/src/index.tsx [hunk 1]
```diff
@@ -294,7 +294,7 @@ const start = (args: string[]) => {
     UI.init()
 
     ipcRenderer.on("menu-item-click", (_evt, message) => {
-        instance.command("normal! " + message)
+        instance.command("exec \":normal! " + message + "\"")
```
Comment (justinmk) [inline browser/src/index.tsx]: Instead of using command() and then doing the escaping here, one could use `nvim_feedkeys()` (which takes same options as VimL `feedkeys()`). Assuming that's mapped to `instance.feedkeys()`,

    instance.feedkeys(message, "n", false)

**Comment by bert88sta** [comment]
Just wrote a fix,  will make a PR in a minute here.

File: browser/src/index.tsx (hunk 1 above)
Comment (keforbes) [inline browser/src/index.tsx]: @justinmk, I tried implementing this with `feedkeys` but `\<c-r>` still doesn't get interpreted.  Any idea why I can't send a Ctrl key to `feedkeys()`?

Comment (justinmk) [inline browser/src/index.tsx]: Hmm, this works from the nvim command line:

    :call nvim_feedkeys("\<c-r>", 'n', v:false)

But of course that "escaped" keycode `"\<c-r>"` is a special thing that won't work outside of vim-land. Using the API from something like python or oni, one would need to send the raw ^R byte (however one's client represents "octal 22"):

    :call nvim_feedkeys("\022", 'n', v:false)

Yuck, that's actually worse than sending the literal string `"norm! "\<c-r>"` to nvim_command().

`nvim_input()` is much more convenient in this regard: `nvim_input('<c-r>')` does what you might expect. But it is raw user input, so one can't disable mappings. 

I should have realized this when I suggested feedkeys(), my mistake.

**Comment by extr0py** [comment]
Good catch @keforbes , sorry I missed this when merging in
